---
plugin: google.cloud.gcp_compute
projects:
  - "{{ lookup('env', 'GCP_PROJECT') }}"
auth_kind: serviceaccount
service_account_file: "{{ lookup('env', 'GCP_SA_FILE') }}"
filters:
  - labels.platform = order-platform
keyed_groups:
  - key: labels.role
    prefix: role
hostnames:
  - name
compose:
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
