services:
  order-service:
    build: ../services/order-service
    environment:
      NOTIFICATION_URL: http://notification-service:8000
    ports: ["8080:8080"]
    depends_on: [notification-service]

  notification-service:
    build: ../services/notification-service
    ports: ["8000:8000"]

  node-exporter:
    image: prom/node-exporter:v1.8.2
    ports: ["9100:9100"]

  prometheus:
    image: prom/prometheus:v2.54.1
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/rules:/etc/prometheus/rules:ro
    ports: ["9090:9090"]

  grafana:
    image: grafana/grafana:11.2.0
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    ports: ["3000:3000"]
    depends_on: [prometheus]
